import { CalendarDays, TrendingUp, Sparkles, ArrowUpRight } from 'lucide-react';
import type { AppData, Garment } from '../types';
import GarmentArt from '../components/GarmentArt';
export default function History({ data, onEdit, onCreate }: {
    data: AppData;
    onEdit: (g: Garment) => void;
    onCreate: () => void;
}) {
    const sorted = [...data.garments].sort((a, b) => b.wearCount - a.wearCount);
    const most = sorted[0], least = sorted[sorted.length - 1];
    const colors = Object.entries(data.garments.reduce<Record<string, {
        count: number;
        hex: string;
    }>>((a, g) => { a[g.color] ??= { count: 0, hex: g.colorHex }; a[g.color].count += g.wearCount; return a; }, {})).filter(([, v]) => v.count > 0).sort((a, b) => b[1].count - a[1].count).slice(0, 5);
    const max = colors[0]?.[1].count || 1;
    const cats = Object.entries(data.garments.reduce<Record<string, number>>((a, g) => { a[g.category] = (a[g.category] || 0) + 1; return a; }, {})).sort((a, b) => b[1] - a[1]);
    return <div className="page"><div className="page-heading"><div><p className="eyebrow">IL TUO STILE, NEL TEMPO</p><h1>Giorno dopo giorno.</h1><p>Riscopri cosa ami. Dai spazio a quello che aspetta.</p></div><span className="soft-pill"><CalendarDays size={15}/>{data.history.length} look indossati</span></div><div className="history-insights">{[{ garment: most, title: 'IL TUO PUNTO FERMO', icon: TrendingUp, empty: 'Nessun capo ancora' }, { garment: least, title: 'DA RISCOPRIRE', icon: Sparkles, empty: 'Aggiungi un capo' }].map(({ garment, title, icon: Icon, empty }) => <button className="usage-card" key={title} onClick={() => garment && onEdit(garment)} disabled={!garment}><div><p className="eyebrow"><Icon size={13}/>{title}</p><h3>{garment?.name || empty}</h3><p>{garment ? `${garment.wearCount} ${garment.wearCount === 1 ? 'volta indossato' : 'volte indossato'}` : 'Il tuo stile inizia da una foto.'}</p></div>{garment && <div className="usage-art"><GarmentArt garment={garment}/></div>}<ArrowUpRight className="usage-arrow" size={17}/></button>)}<div className="colors-card"><p className="eyebrow">I COLORI CHE VIVI DI PIÙ</p>{colors.length ? colors.map(([name, { count, hex }]) => <div className="color-bar" key={name}><span className="color-dot" style={{ background: hex }}/><span>{name}</span><div><i style={{ width: `${count / max * 100}%`, background: hex }}/></div><strong>{count}</strong></div>) : <p className="muted">Indossa un outfit per scoprire la tua palette.</p>}</div></div>
 <div className="history-layout"><section><div className="section-heading"><h2>Il diario dei tuoi outfit</h2><span className="muted">Dal più recente</span></div>{data.history.length ? <div className="timeline">{[...data.history].sort((a, b) => b.date.localeCompare(a.date)).map(event => <article className="history-event" key={event.id}><div className="event-date"><strong>{new Date(event.date).getDate()}</strong><span>{new Date(event.date).toLocaleDateString('it-IT', { month: 'short', year: '2-digit' })}</span></div><div className="event-content"><h3>{event.name}</h3><p>{event.garmentIds.length} capi · {new Date(event.date).toLocaleDateString('it-IT', { weekday: 'long' })}</p><div className="history-garments">{event.garmentIds.map(id => data.garments.find(g => g.id === id)).filter((g): g is Garment => !!g).map(g => <button key={g.id} onClick={() => onEdit(g)} title={g.name} aria-label={g.name}><GarmentArt garment={g}/></button>)}</div></div></article>)}</div> : <div className="empty-state"><CalendarDays size={42}/><h2>Una pagina ancora da scrivere.</h2><p>Scegli “Indosso questo” per iniziare il tuo diario.</p><button className="button button-primary" onClick={onCreate}>Crea il primo look</button></div>}</section><aside className="distribution-card"><p className="eyebrow">IL TUO GUARDAROBA IN NUMERI</p><h3>Spazio a ogni dettaglio.</h3><div className="distribution-total"><strong>{data.garments.length}</strong><span>capi, tutti tuoi</span></div>{cats.map(([name, count]) => <div className="category-bar" key={name}><div><span>{name}</span><strong>{count}</strong></div><div className="bar-track"><span style={{ width: `${count / data.garments.length * 100}%` }}/></div></div>)}<div className="distribution-note">Le statistiche si aggiornano quando scegli cosa indossare.</div></aside></div></div>;
}
